# Generated by Django 5.1.6 on 2025-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_name',
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
