# Generated by Django 5.1.6 on 2025-03-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_image_name_news_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
        migrations.AddField(
            model_name='news',
            name='image_name',
            field=models.ImageField(null=True, upload_to='news'),
        ),
    ]
